Anuncio Mensagens:

#Coloque o nome do servidor ou qualquer outro nome.
Name: '&5[Anunciar]'

#Configuraçoes do chat, edite do geito que desejar.
Formato: "   >> &6{player}: &f{msg}"

#Edite todas as mensagens dos plugins.
Mensagem1: '&bUtilize: /anunciar <mensagem>'
Mensagem2: '&bVocê precisa de &e@quantidade &bcoins.'
Mensagem3: '&bApenas jogadores &6[VIP] &bpodem utilizar o Anuncio!'

#Coloque o Item que sera utilizado para falar no chat. 
Quantidade: 500