name: SgCraftEssentials
description: SgCraftEssentialsPack
main: br.com.sgcraft.Main
version: 1.0
depend: [Vault]
authors: [Igor Sardinha]
commands:
  buff:
   description: Permite o jogador usar o BUFF
  mc:
   description: Ativa o modo Voo
