MySQL:
  Ativado: false
  Usuario: user
  Senha: pass
  Database: database
  Host: localhost
AutoStart:
  Ativo: false
  Dias:
  - Segunda
  - Terca
  - Quarta
  - Quinta
  - Sexta
  - Sabado
  - Domingo
  Hora: '20:00'
ClanTag: '[%tag%&r] '
Format:
  Ativar: false
  default: '%clan%'
  admin: '%clan%&4'
Premios:
  Mito:
    Ativar: true
    Cmd: setmito @player
  Tag: '&7[&6Gladiador&7] '
  Dinheiro: 350000
Aposta:
  Valor: 5000.0
Config:
  Limite: 15
Timers:
  Preparar:
    Avisos: 3
    TempoEntre: 20
  Iniciando:
    Avisos: 2
    TempoEntre: 10
  Finalizando: 15
Arena:
  Entrada: eventos;-245.7425912697699;35.5;76.43564026212547;153.8985;-0.75017923
  Saida: spawn;0.5;38.0;0.5;225.14883;-6.299997
  Camarote: eventos;-245.5;69.0;76.5;285.44894;-0.3001589
  Castelo: spawn;-5.563504788256228;37.0;-5.375750660874538;136.19891;18.749996
Update: 60
Bans: {}
Top_Vencedores: ' &f&lTop Vencedores do &6&lGLADIADOR&f&l:'
Top_Vencedores_Posicao: ' &c>> &b[&f@posicaoº&b] &f| &r@clan &f- &9[@vitorias] &eWin(s)'
Item:
  Bau1:
  - 2:373:8226:5
  - 5:312:0:1:,enchant1:protecao:4,enchant2:inquebravel:3
  - 8:264:0:10
  - 9:384:0:64
  - 13:364:0:5
  - 18:276:0:1:,enchant1:afiada:4
  - 21:313:0:1:,enchant1:protecao:4,enchant2:inquebravel:3
  - 25:322:1:5
  Bau2:
  - 2:264:0:10
  - 5:364:0:5
  - 8:276:0:1:,enchant1:afiada:4
  - 9:384:0:64
  - 12:311:0:1:,enchant1:protecao:4,enchant2:inquebravel:3
  - 19:373:8233:5
  - 23:310:0:1:,enchant1:protecao:4,enchant2:inquebravel:3
  - 26:322:1:5
LocalBau:
  Bau1: spawn;-33.699999988079064;36.0;-37.556728537548786
  Bau2: spawn;-31.300000011920936;36.0;-36.41623711230197
Vencedores:
ClanVenceu: