Mito: ''
Tag: '&5[MITO DO PVP] &r'
Mensagens:
  Novo: '&5[MITO DO PVP] &c@player e o(a) novo(a) MITO do PVP!'
  Atual: '&5[MITO DO PVP] &c@player e o(a) MITO do PVP!'
  Atual2: '&5[MITO DO PVP] &cSem mito do pvp no momento!'
  Logou: '&5[MITO DO PVP] &c@player logou no servidor!'
