name: SgCraftEss
author: Sardinhagamer_HD
version: 6.0
main: br.com.sgcraft.Main

commands:
  desencantar: 
  anunciar:  
  x9:
  buff:
  vender:
  farms:
  cactocontinuar:
  cactoconstruir:
  limparchat: